
version: 2

sources:
  - name: austin_listings
    database: austin-real-estate-de-project
    schema: austin_new_listings
    description: >
      "Data from HomeHarvest that is batched in hourly"
    tables:

      - name: listings
        columns:
          - name: mls_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null

      - name: pending
        columns:
          - name: mls_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
